name: fetch fuel price

on:
  workflow_dispatch:
  schedule:
    - cron: '15 * * * *' # every hour at **:15

jobs:
  fetch-prices:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch and save price
        env:
          TANKERKOENIG_API_KEY: ${{ secrets.TANKERKOENIG_API_KEY }}
        run: python backend/fetch_prices.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Update: Prices'
          file_pattern: 'data/*.json'
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
          commit_author: 'GitHub Actions Bot <actions@github.com>'